% This script loops through the waveform_average_kinetics folder and groups
% them by experimental conditions: 
% For example:
    % DR+CNO- 1
    % CNO- 2
    % NT- 3
    % NT+saline- 4

% The experimental condition of a cell can be uniquely determined by the date, 
% and the cell_num assigned on that day via a look-up cell_id_index table.  

% Once the waveform averages of all cells have been grouped by their
% experimental conditions, a mega waveform average will be generated by
% taking the average of all cells within each condition.

%% %% Change these accordingly based on how you want to group the data
% in each ALL_EVENTS file, dates can be extracted from the last six digits

%save results
save_results = 1;

%figure on
figure_on = 1;

%experiment name (correpsonding to the sheet name in the cell_id_index
% excel file)
exp_name = 'WT_CP_IP_24CNO';

%where to save grouped files
fp_ap_group = ...,
    'C:\Users\schum\Google_Drive\Lab\Data_analysis\chronic_DREADDs\chronic_hm4di\fI_data_by_groups\firstAP_by_group';

%experimental conditions
exp_con = {'DR_CNO','CNO'};

%import cell_id_index table 
cd('C:\Users\schum\Google_Drive\Lab\Data_analysis\chronic_DREADDs\chronic_hm4di\fI_data_by_groups')
cell_id_index = readtable('cell_id_index.xlsx','Sheet',exp_name);

%location of single action potential files (per cell)
AP_fp = 'C:\Users\schum\Google_Drive\Lab\Data_analysis\chronic_DREADDs\chronic_hm4di\firstAP\';

%% group data by condition

%pre-allocation
all_ap = cell(1,numel(exp_con));

%loop through folder
cd(AP_fp)
all_files = dir;
file_num = numel(all_files)-2;

for fi = 1:file_num
    curr_name = all_files(fi+2).name;
    curr_date = curr_name(1:6);
    
    cy = strcat('20',curr_date(1:2));
    cM = curr_date(3:4);
    cday = curr_date(5:6);
    
    date = datetime(strcat(cy,'-',cM,'-',cday),'InputFormat','y-M-d',...
        'Format', 'M/d/y');
    if ~(ismember(date,cell_id_index.Date))
        continue
    else
        load(all_files(fi+2).name)
        
        for ci = 1:size(V_firstAP,2)
            if sum(V_firstAP(:,ci)) == 0
                continue
            else
                if isempty(find(cell_id_index.Date == date & cell_id_index.Cell_num == ci,1))
                    continue
                else
                
                    row = find(cell_id_index.Date == date & cell_id_index.Cell_num == ci);
                    cond_i = cell_id_index{row,'Cat'};
                    cell_ID = cell_id_index{row,'Cell_ID'};
                    all_ap{1,cond_i}(:,cell_ID) = V_firstAP(:,ci);
                end
            end
        end
    end
        
end


%% calculate meta average
%pre-allocation
all_meta_ap = cell(1,numel(exp_con));

%calculate average for each row
for ei = 1:numel(exp_con)
    for ri = 1:size(all_ap{1,ei},1)
        all_meta_ap{1,ei}(ri,1) = nanmean(all_ap{1,ei}(ri,:));
    end
end

%% plot

condition1 = all_meta_ap{1,2};
condition2 = all_meta_ap{1,1};

%color code
color1 = [250 128 114]./255; %salmon
color2 = [70 130 180]./255; %steel blue
color3 = [255 203 164]./255; %deep peach
color4 = [153 186 221]./255; %carolina blue

plot_range = (1:110);

if figure_on == 1
    figure();
    plot(condition1(plot_range),'Color',color1,'LineWidth',4)
    hold on
    plot(condition2(plot_range),'Color',color2,'LineWidth',4)
    %hold on
    %plot(meta_ave.DR_CNO_24(20:110),'Color',[0.27 0.51 0.71],'LineWidth',4)
    title('First AP at rheobase step')
    legend('CNO','DR+CNO')
    
    %draw scale
    plot([60; 80],[0; 0], '-k',[60;60],[0; 10], '-k', 'LineWidth',2)
    text(60, 5, '10 mV', 'HorizontalAlignment', 'right')
    text(70, -5, '20 ms', 'HorizontalAlignment', 'center')
    
    box off
    hold off
end

%% save to file

if save_results == 1
    cd(fp_ap_group)
    save(strcat(exp_name,'.mat'),'all_ap','all_meta_ap','cell_id_index')
end